package com.haze.mobile.crypto

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.jsonPrimitive
import kotlinx.serialization.json.put
import org.bouncycastle.crypto.agreement.X25519Agreement
import org.bouncycastle.crypto.digests.SHA256Digest
import org.bouncycastle.crypto.generators.HKDFBytesGenerator
import org.bouncycastle.crypto.generators.X25519KeyPairGenerator
import org.bouncycastle.crypto.params.HKDFParameters
import org.bouncycastle.crypto.params.X25519KeyGenerationParameters
import org.bouncycastle.crypto.params.X25519PrivateKeyParameters
import org.bouncycastle.crypto.params.X25519PublicKeyParameters
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import java.security.KeyPairGenerator
import java.security.SecureRandom
import java.security.spec.ECGenParameterSpec
import javax.crypto.Cipher
import javax.crypto.KeyAgreement
import javax.crypto.spec.GCMParameterSpec
import javax.crypto.spec.SecretKeySpec

/**
 * Cross-implementation guard for the browser encryption layer.
 *
 * The same page (assets/web/index.html) talks to a Python host and to this one,
 * so the two must derive identical keys and produce interchangeable ciphertext.
 * The vectors below were generated by haze/crypto/webe2e.py; if either side
 * drifts — a changed HKDF label, a different AEAD, another base64 flavour —
 * these fail instead of browser guests silently failing to join a phone-hosted
 * room.
 */
class WebE2ETest {

    private val json = Json { ignoreUnknownKeys = true }

    // ── Vectors from webe2e.py ───────────────────────────────────────────
    private val sessionKeyHex = "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f"
    private val trafficKeyHex = "014bb61130ef2dda66d66e15644af347b818d24a32a7d6ffdaff969fc8b7fc5a"
    private val pyNonce = "M4+/UJXRVcDukYp1"
    private val pyCiphertext =
        "XokCcZ5vxJxXD6YT+7dkqrvGflFOQkarnAjJ3QLbYqb9QGWXegN6z9GRxc0FRJm3wJjZGkY7w1Yy" +
            "iTvn4A7V+Nym88zqjlsaSsgGclaD0ue07pFnnuarXNk="

    @Test
    fun trafficKeyMatchesPython() {
        val derived = WebE2E.deriveTrafficKey(hex(sessionKeyHex))
        assertEquals(
            "HKDF label or hash drifted from webe2e.py",
            trafficKeyHex, derived.joinToString("") { "%02x".format(it) },
        )
    }

    @Test
    fun trafficKeyIsNotTheSessionKey() {
        // Domain separation: the same bytes must not be used with both ciphers.
        assertNotEquals(sessionKeyHex, trafficKeyHex)
    }

    @Test
    fun decryptsAnEnvelopeProducedByPython() {
        val envelope = buildJsonObject {
            put("type", "encrypted"); put("nonce", pyNonce); put("ciphertext", pyCiphertext)
        }
        val plain = WebE2E.decrypt(hex(trafficKeyHex), envelope)
        val obj = json.parseToJsonElement(plain) as JsonObject
        assertEquals("chat", obj["type"]?.jsonPrimitive?.content)
        assertEquals("python_host", obj["nick"]?.jsonPrimitive?.content)
        assertEquals("cross-language test", obj["content"]?.jsonPrimitive?.content)
    }

    @Test
    fun ownEnvelopeRoundTrips() {
        val key = hex(trafficKeyHex)
        val env = WebE2E.encrypt(key, buildJsonObject { put("type", "chat"); put("content", "merhaba") })
        assertEquals("encrypted", env["type"]?.jsonPrimitive?.content)
        val obj = json.parseToJsonElement(WebE2E.decrypt(key, env)) as JsonObject
        assertEquals("merhaba", obj["content"]?.jsonPrimitive?.content)
    }

    @Test
    fun plaintextNeverAppearsInCiphertext() {
        val env = WebE2E.encrypt(hex(trafficKeyHex), buildJsonObject { put("content", "GIZLI") })
        val raw = String(java.util.Base64.getDecoder().decode(env["ciphertext"]!!.jsonPrimitive.content),
                         Charsets.ISO_8859_1)
        assertTrue(!raw.contains("GIZLI"))
    }

    @Test
    fun tamperedCiphertextIsRejected() {
        val key = hex(trafficKeyHex)
        val env = WebE2E.encrypt(key, buildJsonObject { put("content", "hello") })
        val bytes = java.util.Base64.getDecoder().decode(env["ciphertext"]!!.jsonPrimitive.content)
        bytes[0] = (bytes[0].toInt() xor 1).toByte()
        val forged = buildJsonObject {
            put("type", "encrypted")
            put("nonce", env["nonce"]!!.jsonPrimitive.content)
            put("ciphertext", java.util.Base64.getEncoder().encodeToString(bytes))
        }
        assertThrowsWebCrypto { WebE2E.decrypt(key, forged) }
    }

    @Test
    fun wrongKeyIsRejected() {
        val env = WebE2E.encrypt(hex(trafficKeyHex), buildJsonObject { put("content", "hello") })
        assertThrowsWebCrypto { WebE2E.decrypt(ByteArray(32), env) }
    }

    @Test
    fun unknownAlgorithmIsRejected() {
        assertThrowsWebCrypto { WebE2E.wrapTrafficKey("AAAA", "RSA", ByteArray(32)) }
    }

    @Test
    fun malformedPublicKeyIsRejected() {
        assertThrowsWebCrypto { WebE2E.wrapTrafficKey("!!!not base64!!!", WebE2E.ALG_X25519, ByteArray(32)) }
    }

    /** Acts as the browser for X25519: agree, unwrap, compare. */
    @Test
    fun x25519HandshakeDeliversTheTrafficKey() {
        val trafficKey = hex(trafficKeyHex)
        val gen = X25519KeyPairGenerator().apply { init(X25519KeyGenerationParameters(SecureRandom())) }
        val pair = gen.generateKeyPair()
        val clientPriv = pair.private as X25519PrivateKeyParameters
        val clientPub = (pair.public as X25519PublicKeyParameters).encoded

        val welcome = WebE2E.wrapTrafficKey(b64(clientPub), WebE2E.ALG_X25519, trafficKey)
        val hostPub = unb64(welcome["pubkey"]!!.jsonPrimitive.content)
        val shared = ByteArray(32)
        X25519Agreement().apply {
            init(clientPriv)
            calculateAgreement(X25519PublicKeyParameters(hostPub, 0), shared, 0)
        }
        assertTrue(unwrap(shared, welcome).contentEquals(trafficKey))
    }

    /** Same for P-256, the fallback used by browsers without X25519. */
    @Test
    fun p256HandshakeDeliversTheTrafficKey() {
        val trafficKey = hex(trafficKeyHex)
        val gen = KeyPairGenerator.getInstance("EC").apply {
            initialize(ECGenParameterSpec("secp256r1"), SecureRandom())
        }
        val pair = gen.generateKeyPair()
        // Raw uncompressed point, the shape WebCrypto exports.
        val encoded = pair.public.encoded
        val clientPub = encoded.copyOfRange(encoded.size - 65, encoded.size)
        assertEquals("uncompressed point marker", 0x04.toByte(), clientPub[0])

        val welcome = WebE2E.wrapTrafficKey(b64(clientPub), WebE2E.ALG_P256, trafficKey)
        val hostRaw = unb64(welcome["pubkey"]!!.jsonPrimitive.content)
        assertEquals(65, hostRaw.size)

        val hostKey = java.security.KeyFactory.getInstance("EC").generatePublic(
            java.security.spec.X509EncodedKeySpec(p256Prefix + hostRaw)
        )
        val shared = KeyAgreement.getInstance("ECDH").run {
            init(pair.private); doPhase(hostKey, true); generateSecret()
        }
        assertTrue(unwrap(shared, welcome).contentEquals(trafficKey))
    }

    // ── helpers ──────────────────────────────────────────────────────────

    private val p256Prefix = byteArrayOf(
        0x30, 0x59, 0x30, 0x13, 0x06, 0x07, 0x2A, 0x86.toByte(), 0x48, 0xCE.toByte(),
        0x3D, 0x02, 0x01, 0x06, 0x08, 0x2A, 0x86.toByte(), 0x48, 0xCE.toByte(), 0x3D,
        0x03, 0x01, 0x07, 0x03, 0x42, 0x00,
    )

    private fun unwrap(shared: ByteArray, welcome: JsonObject): ByteArray {
        val wrapKey = ByteArray(32)
        HKDFBytesGenerator(SHA256Digest()).apply {
            init(HKDFParameters(shared, null, "haze-web-handshake-v1".toByteArray()))
        }.generateBytes(wrapKey, 0, 32)
        val cipher = Cipher.getInstance("AES/GCM/NoPadding")
        cipher.init(
            Cipher.DECRYPT_MODE, SecretKeySpec(wrapKey, "AES"),
            GCMParameterSpec(128, unb64(welcome["nonce"]!!.jsonPrimitive.content)),
        )
        return cipher.doFinal(unb64(welcome["ciphertext"]!!.jsonPrimitive.content))
    }

    private fun assertThrowsWebCrypto(block: () -> Unit) {
        val err = runCatching(block).exceptionOrNull()
        assertTrue("expected WebCryptoException, got $err", err is WebE2E.WebCryptoException)
    }

    private fun hex(s: String) = ByteArray(s.length / 2) {
        s.substring(it * 2, it * 2 + 2).toInt(16).toByte()
    }

    private fun b64(b: ByteArray) = java.util.Base64.getEncoder().encodeToString(b)
    private fun unb64(s: String) = java.util.Base64.getDecoder().decode(s)
}
